# Generated by Django 4.1.4 on 2023-04-19 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_salesman'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='basket',
        ),
    ]
