# Generated by Django 4.1.4 on 2023-04-21 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesmans',
            name='id_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='salesmans',
            name='items',
        ),
        migrations.AddField(
            model_name='salesmans',
            name='items',
            field=models.ManyToManyField(to='app.item'),
        ),
    ]
