# Generated by Django 4.1.4 on 2023-04-23 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_salesmans_id_user_remove_salesmans_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='basket',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.basket'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
