# Generated by Django 4.1.4 on 2023-04-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_item_price_remove_basket_items_alter_item_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='photo',
            field=models.ImageField(null=True, upload_to='items_photo'),
        ),
    ]
